[package]
name = "archflow-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace dependencies
archflow-core = { path = "../archflow-core" }
archflow-geometry = { path = "../archflow-geometry" }
archflow-primitives = { path = "../archflow-primitives" }
web-sys.workspace = true

[lib]
path = "src/lib.rs"
