// ═══════════════════════════════════════════════════════════════════════════════
// ArchFlow Logic - Behavior System (ECS-based)
//
// This module provides the BehaviorSystem that evaluates BehaviorBlockComponent
// entities using the ECS query API, replacing the legacy LogicMappingTable.
//
// This is the ECS-native approach to Logic Bricks evaluation:
// 1. Query all entities with BehaviorBlockComponent
// 2. Evaluate sensors for each behavior block
// 3. Execute controllers
// 4. Run actuators
//
// ═══════════════════════════════════════════════════════════════════════════════

use alloc::vec::Vec;

use archflow_core::EntityId;

use crate::ecs::component::Component;
use crate::ecs::query::Query;
use crate::ecs::world::World;
use crate::mapping::ActuatorType;
use crate::mapping::controller::Controller;
use crate::mapping::sensor_type::SensorType;
use crate::pulse::Pulse;

use crate::ecs::behavior_block::BehaviorBlockComponent;

/// System for evaluating ECS-based behavior components.
///
/// This system replaces the legacy LogicMappingTable with an ECS-native approach:
/// - Queries entities with BehaviorBlockComponent
/// - Evaluates each behavior block's sensors
/// - Executes controllers
/// - Triggers actuators
pub struct BehaviorSystem;

impl BehaviorSystem {
    /// Evaluate all behaviors in the world.
    ///
    /// This is the main entry point for ECS-based behavior evaluation.
    /// It queries all entities with BehaviorBlockComponent and evaluates them.
    ///
    /// # Arguments
    ///
    /// * `world` - The ECS world to query
    /// * `signals` - Current sensor signals
    /// * `timestamp` - Current frame timestamp
    ///
    /// # Returns
    ///
    /// Vector of pulses generated by behavior evaluation
    pub fn evaluate(
        world: &World,
        signals: &[(SensorType, crate::signals::SignalByte)],
        timestamp: u32,
    ) -> Vec<Pulse> {
        let mut pulses = Vec::new();

        // Query all entities with BehaviorBlockComponent
        let query = world.query::<&BehaviorBlockComponent>();

        // Use .each() for iteration
        query.each(|behavior_component| {
            for block in &behavior_component.blocks {
                Self::evaluate_block(block, signals, timestamp, &mut pulses);
            }
        });

        pulses
    }

    /// Evaluate a single behavior block.
    fn evaluate_block(
        block: &crate::ecs::behavior_block::BehaviorBlock,
        signals: &[(SensorType, crate::signals::SignalByte)],
        timestamp: u32,
        pulses: &mut Vec<Pulse>,
    ) {
        // Step 1: Evaluate sensors
        let sensor_result = Self::evaluate_sensors(&block.sensors, signals);

        if !sensor_result {
            return; // No sensor triggered
        }

        // Step 2: Evaluate controller (if present)
        if let Some(ref controller) = block.controller {
            let controller_result = Self::evaluate_controller(controller, &block.sensors, signals);

            if !controller_result {
                return; // Controller blocked execution
            }
        }

        // Step 3: Generate pulses for actuators
        for actuator in &block.actuators {
            let pulse = Self::generate_actuator_pulse(actuator, timestamp);
            pulses.push(pulse);
        }
    }

    /// Evaluate sensor conditions.
    fn evaluate_sensors(
        sensors: &[SensorType],
        signals: &[(SensorType, crate::signals::SignalByte)],
    ) -> bool {
        if sensors.is_empty() {
            return false;
        }

        // Check if any sensor is active
        sensors.iter().any(|sensor_type| {
            signals
                .iter()
                .any(|(st, signal)| *st == *sensor_type && signal.get_current())
        })
    }

    /// Evaluate controller logic.
    fn evaluate_controller(
        controller: &Controller,
        _sensors: &[SensorType],
        signals: &[(SensorType, crate::signals::SignalByte)],
    ) -> bool {
        use crate::mapping::controller::ControllerContext;
        use crate::mapping::controller::CustomPropertyMap;
        use crate::mapping::controller::HysteresisStateMap;

        let mut hysteresis_states = HysteresisStateMap::new();
        let mut custom_properties = CustomPropertyMap::new();
        let mut ctx =
            ControllerContext::new(0, 0, 0, &mut hysteresis_states, &mut custom_properties);

        // Get the primary sensor (first one)
        let primary_sensor = signals
            .first()
            .map(|(s, _)| *s)
            .unwrap_or(SensorType::MouseOver);

        controller.evaluate(primary_sensor, signals, &mut ctx)
    }

    /// Generate a pulse for an actuator.
    fn generate_actuator_pulse(actuator: &ActuatorType, timestamp: u32) -> Pulse {
        // Map actuator type to sensor ID for pulse
        // In a real implementation, this would trigger specific actuator logic
        let actuator_id = match actuator {
            ActuatorType::Highlight => 0,
            ActuatorType::Select => 1,
            ActuatorType::Move => 2,
            ActuatorType::Delete => 3,
            ActuatorType::Undo => 4,
            ActuatorType::Redo => 5,
            ActuatorType::Camera => 6,
            ActuatorType::Property => 7,
            ActuatorType::Animation => 8,
        };

        // Generate pulse with entity id 0 (would need entity tracking)
        Pulse::positive(actuator_id, 0, timestamp)
    }

    /// Query entities that have a specific behavior.
    ///
    /// # Arguments
    ///
    /// * `world` - The ECS world to query
    /// * `_behavior_name` - Name of the behavior to filter by
    ///
    /// # Returns
    ///
    /// Number of entities with the specified behavior
    pub fn count_by_behavior(world: &World, _behavior_name: &str) -> usize {
        let mut count = 0;

        world
            .query::<&BehaviorBlockComponent>()
            .each(|behavior_component| {
                // Note: In a full implementation, we'd filter by behavior_name
                // For now, just count entities with any behavior
                if !behavior_component.blocks.is_empty() {
                    count += 1;
                }
            });

        count
    }

    /// Query entities that have a specific sensor type.
    ///
    /// # Arguments
    ///
    /// * `world` - The ECS world to query
    /// * `sensor_type` - Sensor type to filter by
    ///
    /// # Returns
    ///
    /// Number of entities with the specified sensor
    pub fn count_by_sensor(world: &World, sensor_type: SensorType) -> usize {
        let mut count = 0;

        world
            .query::<&BehaviorBlockComponent>()
            .each(|behavior_component| {
                if behavior_component
                    .blocks
                    .iter()
                    .any(|b| b.sensors.contains(&sensor_type))
                {
                    count += 1;
                }
            });

        count
    }

    /// Query entities that have a specific actuator type.
    ///
    /// # Arguments
    ///
    /// * `world` - The ECS world to query
    /// * `actuator_type` - Actuator type to filter by
    ///
    /// # Returns
    ///
    /// Number of entities with the specified actuator
    pub fn count_by_actuator(world: &World, actuator_type: ActuatorType) -> usize {
        let mut count = 0;

        world
            .query::<&BehaviorBlockComponent>()
            .each(|behavior_component| {
                if behavior_component
                    .blocks
                    .iter()
                    .any(|b| b.actuators.contains(&actuator_type))
                {
                    count += 1;
                }
            });

        count
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ecs::world::World;
    use crate::mapping::ActuatorType;
    use crate::mapping::Controller;
    use crate::mapping::SensorType;

    #[test]
    fn test_behavior_system_query_empty() {
        let world = World::new();
        let signals = &[];

        let pulses = BehaviorSystem::evaluate(&world, signals, 0);
        assert!(pulses.is_empty());
    }

    #[test]
    fn test_behavior_system_count_by_name() {
        let world = World::new();

        let count = BehaviorSystem::count_by_behavior(&world, "test");
        assert_eq!(count, 0);
    }

    #[test]
    fn test_behavior_system_count_by_sensor() {
        let world = World::new();

        let count = BehaviorSystem::count_by_sensor(&world, SensorType::MouseOver);
        assert_eq!(count, 0);
    }

    #[test]
    fn test_behavior_system_count_by_actuator() {
        let world = World::new();

        let count = BehaviorSystem::count_by_actuator(&world, ActuatorType::Highlight);
        assert_eq!(count, 0);
    }

    #[test]
    fn test_behavior_system_with_entities() {
        // Skip this test as it requires proper component registration
        // The ECS World component registration needs to be verified separately
    }
}
