[package]
name = "archflow-editing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
archflow-core = { path = "../archflow-core" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lib]
doctest = false
