// ═══════════════════════════════════════════════════════════════════════════════
// ArchFlow Web - Event Ring Buffer WASM Bindings
//
// EPIC-WEB-013 HU-001: Export EventRingBuffer to JavaScript
//
// This module provides WASM bindings for the event ring buffer, allowing
// JavaScript to poll events generated by the Rust logic system.
// ═══════════════════════════════════════════════════════════════════════════════

#![allow(missing_docs)]

use alloc::vec::Vec;
use wasm_bindgen::prelude::*;

use crate::logic::{JsLogicEventData, LogicSystemWasm};

// ═══════════════════════════════════════════════════════════════════════════════
// EVENT EXPORT STRUCTURE
// ═══════════════════════════════════════════════════════════════════════════════

/// Structure representing a single event for JavaScript consumption
///
/// This is a simplified version of LogicEvent that's easy to serialize
/// across the WASM boundary.
#[wasm_bindgen]
pub struct JsLogicEvent {
    /// Event type identifier (corresponds to LogicEventType discriminant)
    event_type: u8,

    /// Entity ID that triggered the event
    entity_id: u32,

    /// Timestamp in microseconds
    timestamp_us: u64,

    /// Additional data depending on event type:
    /// - ProximityAlert: f32 distance
    /// - DragStarted/DragEnded: f32 x, f32 y position
    /// - BoxSelection: u32 count
    /// - HoverChanged: u32 entity_id (or 0 for none)
    data_1: f32,
    data_2: f32,
    data_3: u32,
}

#[wasm_bindgen]
impl JsLogicEvent {
    /// Get the event type
    #[wasm_bindgen(getter)]
    pub fn event_type(&self) -> u8 {
        self.event_type
    }

    /// Get the entity ID
    #[wasm_bindgen(getter)]
    pub fn entity_id(&self) -> u32 {
        self.entity_id
    }

    /// Get the timestamp
    #[wasm_bindgen(getter)]
    pub fn timestamp_us(&self) -> u64 {
        self.timestamp_us
    }

    /// Get data_1 (context-dependent)
    #[wasm_bindgen(getter)]
    pub fn data_1(&self) -> f32 {
        self.data_1
    }

    /// Get data_2 (context-dependent)
    #[wasm_bindgen(getter)]
    pub fn data_2(&self) -> f32 {
        self.data_2
    }

    /// Get data_3 (context-dependent)
    #[wasm_bindgen(getter)]
    pub fn data_3(&self) -> u32 {
        self.data_3
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// EVENT RING BUFFER WASM EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

/// WASM wrapper for accessing the event ring buffer
///
/// This provides JavaScript access to events generated by the logic system.
#[wasm_bindgen]
pub struct EventRingBufferWasm {
    // No stored state - we access through LogicSystemWasm
}

#[wasm_bindgen]
impl EventRingBufferWasm {
    /// Create a new EventRingBuffer accessor
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {}
    }

    /// Drain all pending events from the logic system
    ///
    /// This method returns all events currently in the ring buffer and
    /// clears the buffer for the next frame.
    ///
    /// # Returns
    ///
    /// Array of JsLogicEvent objects representing all pending events
    ///
    /// # JavaScript Example
    ///
    /// ```javascript
    /// const eventBuffer = new EventRingBufferWasm();
    /// const events = eventBuffer.drain(logicSystem);
    ///
    /// for (const event of events) {
    ///   console.log(`Event ${event.event_type} from entity ${event.entity_id}`);
    /// }
    /// ```
    #[wasm_bindgen]
    pub fn drain(&mut self, system: &mut LogicSystemWasm) -> Vec<JsLogicEvent> {
        // Get events from the logic system
        let events_data = system.drain_events();

        // Convert to WASM-friendly format with context data
        events_data
            .into_iter()
            .map(|data| {
                // Extract context data based on event type
                let (data_1, data_2, data_3) = match data.event_type {
                    0 => (0.0, 0.0, 0), // EntitySelected
                    1 => (0.0, 0.0, 0), // ProximityAlert - would need distance
                    2 => (0.0, 0.0, 0), // DragStarted - would need position
                    3 => (0.0, 0.0, 0), // DragEnded - would need position
                    4 => (0.0, 0.0, 0), // BoxSelectionCompleted - would need count
                    5 => (0.0, 0.0, 0), // HoverChanged - would need entity_id
                    _ => (0.0, 0.0, 0),
                };

                JsLogicEvent {
                    event_type: data.event_type,
                    entity_id: data.entity_id,
                    timestamp_us: data.timestamp_us,
                    data_1,
                    data_2,
                    data_3,
                }
            })
            .collect()
    }

    /// Get the number of events currently in the buffer
    ///
    /// # Returns
    ///
    /// Number of pending events
    #[wasm_bindgen]
    pub fn event_count(&mut self, system: &mut LogicSystemWasm) -> usize {
        system.event_count()
    }

    /// Check if there are any pending events
    ///
    /// # Returns
    ///
    /// true if there are pending events, false otherwise
    #[wasm_bindgen]
    pub fn has_events(&mut self, system: &mut LogicSystemWasm) -> bool {
        system.has_events()
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// EVENT TYPE CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════════

/// Event type constants for JavaScript
///
/// These correspond to the LogicEventType enum in Rust
#[wasm_bindgen]
pub struct EventType;

#[wasm_bindgen]
impl EventType {
    /// Entity was selected/deselected
    #[wasm_bindgen(getter)]
    pub fn entity_selected() -> u8 {
        0
    }

    /// Proximity threshold crossed
    #[wasm_bindgen(getter)]
    pub fn proximity_alert() -> u8 {
        1
    }

    /// Drag operation started
    #[wasm_bindgen(getter)]
    pub fn drag_started() -> u8 {
        2
    }

    /// Drag operation ended
    #[wasm_bindgen(getter)]
    pub fn drag_ended() -> u8 {
        3
    }

    /// Box selection completed
    #[wasm_bindgen(getter)]
    pub fn box_selection_completed() -> u8 {
        4
    }

    /// Hover state changed
    #[wasm_bindgen(getter)]
    pub fn hover_changed() -> u8 {
        5
    }
}
