[package]
name = "archflow-export"
version.workspace = true
edition.workspace = true

[dependencies]
archflow-core = { path = "../archflow-core" }
archflow-diagram = { path = "../archflow-diagram" }
archflow-engine = { path = "../archflow-engine" }
bytemuck = { workspace = true }
fixedbitset = { workspace = true }
flatbuffers = { workspace = true }
serde = { workspace = true }
