// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a color for JS interop
 */
export type JsColor = { r: number, g: number, b: number, a: number, };
