// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JavaScript-compatible layer info
 */
export type JsLayerInfo = { id: string, name: string, visible: boolean, locked: boolean, opacity: number, zOrder: number, shapeCount: number, c4Level: string, };
