// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsRect } from "./JsRect";

/**
 * Represents selection for JS interop
 */
export type JsSelection = { shapeIds: Array<string>, bounds: JsRect, isBox: boolean, };
