// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsColor } from "./JsColor";

/**
 * Represents a shape for JS interop
 */
export type JsShape = { id: string, shapeType: string, x: number, y: number, width: number, height: number, rotation: number, fillColor: JsColor, strokeColor: JsColor | null, strokeWidth: number, opacity: number, layerId: string, selected: boolean, };
