// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JavaScript-compatible shape creation data
 */
export type JsShapeCreationData = { shapeType: string, x: number, y: number, width: number, height: number, fillColor: string | null, strokeColor: string | null, strokeWidth: number | null, opacity: number | null, };
