// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shape definition for custom previews
 */
export type ShapeDefinition = { shape_type: string, width: number, height: number, stroke_color: string, fill_color: string, };
