// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible wrapper for Color
 */
export type TsColor = { 
/**
 * Red component (0.0 - 1.0)
 */
r: number, 
/**
 * Green component (0.0 - 1.0)
 */
g: number, 
/**
 * Blue component (0.0 - 1.0)
 */
b: number, 
/**
 * Alpha component (0.0 - 1.0)
 */
a: number, };
