// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TsVec2 } from "./TsVec2";

/**
 * TypeScript-compatible wrapper for Rect
 */
export type TsRect = { 
/**
 * Minimum corner (top-left)
 */
min: TsVec2, 
/**
 * Maximum corner (bottom-right)
 */
max: TsVec2, };
