[package]
name = "archflow-engine"
version.workspace = true
edition.workspace = true

[dependencies]
archflow-core = { path = "../archflow-core", features = ["std"] }
fixedbitset = { workspace = true }
heapless = { workspace = true }

[dev-dependencies]
archflow-core = { path = "../archflow-core", features = ["std"] }
