[package]
name = "archflow-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace dependencies
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }

archflow-core = { path = "../archflow-core" }
archflow-geometry = { path = "../archflow-geometry" }

[lib]
path = "src/lib.rs"
