[package]
name = "archflow-renderers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace dependencies
glam.workspace = true
bytemuck.workspace = true
wgpu.workspace = true
thiserror.workspace = true
raw-window-handle = "0.6"
archflow-records = { path = "../archflow-records" }
archflow-geometry = { path = "../archflow-geometry" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false

[lib]
path = "src/lib.rs"
