[package]
name = "archflow-renderers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace dependencies
glam.workspace = true
bytemuck.workspace = true
wgpu.workspace = true
thiserror.workspace = true
archflow-records = { path = "../archflow-records" }
archflow-geometry = { path = "../archflow-geometry" }

[lib]
path = "src/lib.rs"
