[package]
name = "archflow-ecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace dependencies
bevy_ecs.workspace = true
archflow-core = { path = "../archflow-core" }
archflow-records = { path = "../archflow-records" }
archflow-spatial = { path = "../archflow-spatial" }
archflow-primitives = { path = "../archflow-primitives" }

[lib]
path = "src/lib.rs"
