/**
 * Type declarations for @archflow/web WASM module
 *
 * This module is generated by wasm-pack from the Rust crate archflow-web
 */

declare module "@archflow/web" {
  /**
   * WasmBridge - Main entry point for the ArchFlow WASM bridge
   */
  export class WasmBridge {
    constructor();

    /** Initialize the engine with canvas dimensions */
    initialize(width: number, height: number): void;

    /** Get the underlying engine instance */
    get_engine(): unknown;

    /** Get the input buffer pointer for SharedArrayBuffer communication */
    getInputBufferPtr(): number;

    /** Get the input buffer size */
    getInputBufferSize(): number;

    /** Push an input event to the WASM input processor */
    pushInputEvent(
      eventType: number,
      x: number,
      y: number,
      buttons: number,
      modifiers: number,
    ): void;

    /** Main tick function for the engine loop */
    tick(timestamp: number): void;

    // Entity operations
    spawnEntity(x: number, y: number, width: number, height: number): number;
    moveEntity(entityIndex: number, dx: number, dy: number): void;
    setColor(entityIndex: number, r: number, g: number, b: number, a: number): void;
    setShape(entityIndex: number, shape: number): void;
    setLabel(entityIndex: number, label: string): void;
    setSize(entityIndex: number, width: number, height: number): void;
    setPosition(entityIndex: number, x: number, y: number): void;
    entityCount(): number;
    clear(): void;
    deleteSelected(): void;
    duplicateEntity(entityIndex: number): number;

    // Query operations
    getAliveEntities(): number[];
    getEntityPositionScreen(entityIndex: number): [number, number];
    getEntitySizeScreen(entityIndex: number): [number, number];
    getEntityColorHex(entityIndex: number): string;
    getEntityShape(entityIndex: number): number;
    getEntityLabel(entityIndex: number): string;
    isEntityVisible(entityIndex: number): boolean;
    isEntitySelected(entityIndex: number): boolean;

    // Selection
    selectEntity(entityIndex: number): void;
    clearSelection(): void;
    getSelection(): number[];
    setEntitySelected(entityIndex: number, selected: boolean): void;

    // Camera
    setZoom(zoom: number): void;
    getZoom(): number;
    setCameraCenter(x: number, y: number): void;
    getCameraCenter(): [number, number];

    // History
    undo(): void;
    redo(): void;
    canUndo(): boolean;
    canRedo(): boolean;
    getHistoryState(): string;

    // Serialization
    serializeProject(): Uint8Array;

    // Tools
    setTool(tool: string): void;
    getTool(): string;
  }
}
