/**
 * Type declarations for @archflow/web WASM module
 *
 * This module is generated by wasm-pack from the Rust crate archflow-web
 */

declare module "@archflow/web" {
  /**
   * WasmBridge - Main entry point for the ArchFlow WASM bridge
   */
  export class WasmBridge {
    constructor();

    /** Initialize the engine with canvas dimensions */
    initialize(width: number, height: number): void;

    /** Get the underlying engine instance */
    get_engine(): unknown;

    /** Get the input buffer pointer for SharedArrayBuffer communication */
    get_input_buffer_ptr(): number;

    /** Get the input buffer size */
    static get_input_buffer_size(): number;

    /** Push an input event to the WASM input processor */
    push_input_event(
      eventType: number,
      x: number,
      y: number,
      buttons: number,
      modifiers: number,
    ): void;

    /** Main tick function for the engine loop */
    tick(timestamp: number): void;

    // Entity operations
    spawn_entity(x: number, y: number, width: number, height: number): number;
    move_entity(entityIndex: number, dx: number, dy: number): void;
    set_color(entityIndex: number, r: number, g: number, b: number, a: number): void;
    set_shape(entityIndex: number, shape: number): void;
    set_label(entityIndex: number, label: string): void;
    set_size(entityIndex: number, width: number, height: number): void;
    set_position(entityIndex: number, x: number, y: number): void;
    entity_count(): number;
    clear(): void;
    delete_selected(): void;
    duplicate_entity(entityIndex: number): number;

    // Query operations
    get_alive_entities(): number[];
    get_entity_position_screen(entityIndex: number): [number, number];
    get_entity_size_screen(entityIndex: number): [number, number];
    get_entity_color_hex(entityIndex: number): string;
    get_entity_shape(entityIndex: number): number;
    get_entity_label(entityIndex: number): string;
    is_entity_visible(entityIndex: number): boolean;
    is_entity_selected(entityIndex: number): boolean;

    // Selection
    select_entity(entityIndex: number): void;
    clear_selection(): void;
    get_selection(): number[];
    set_entity_selected(entityIndex: number, selected: boolean): void;

    // Camera
    set_zoom(zoom: number): void;
    get_zoom(): number;
    set_camera_center(x: number, y: number): void;
    get_camera_center(): [number, number];

    // History
    undo(): void;
    redo(): void;
    can_undo(): boolean;
    can_redo(): boolean;
    get_history_state(): string;

    // Serialization
    serialize_project(): Uint8Array;

    // Tools
    set_tool(tool: string): void;
    get_tool(): string;
  }
}
