//! ArchFlow Event Sourcing - Core module for Git-like event history
//!
//! Provides:
//! - DomainEvent enum with all event types
//! - EventStore for persistence
//! - EventJournal for undo/redo functionality
//! - Snapshot support for large state

use crate::EntityId;
use serde::{Deserialize, Serialize};
use std::time::Duration;

pub mod event;
pub mod event_journal;
pub mod event_store;
pub mod snapshot;

pub use event::{DomainEvent, EventMetadata};
pub use event_journal::{EventJournal, JournalEntry, JournalError, UndoRedoStack};
pub use event_store::{EventStore, EventStoreError, StoredEvent};
pub use snapshot::{Snapshot, SnapshotError, SnapshotManager};

/// Version of the event schema for forward compatibility
pub const EVENT_SCHEMA_VERSION: u32 = 1;

/// Maximum events before forcing a snapshot
const DEFAULT_SNAPSHOT_THRESHOLD: usize = 1000;

/// Commands that can be issued to modify the document
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Command {
    /// Create a new primitive/shape
    CreatePrimitive {
        primitive_id: EntityId,
        primitive_type: String,
        position: (f32, f32),
        size: (f32, f32),
    },
    /// Move a primitive
    MovePrimitive {
        primitive_id: EntityId,
        from: (f32, f32),
        to: (f32, f32),
    },
    /// Resize a primitive
    ResizePrimitive {
        primitive_id: EntityId,
        from: (f32, f32),
        to: (f32, f32),
    },
    /// Delete a primitive
    DeletePrimitive { primitive_id: EntityId },
    /// Add a connection between two ports
    AddConnection {
        connection_id: EntityId,
        source_port: EntityId,
        target_port: EntityId,
    },
    /// Remove a connection
    RemoveConnection { connection_id: EntityId },
    /// Group primitives
    Group {
        group_id: EntityId,
        primitive_ids: Vec<EntityId>,
    },
    /// Ungroup primitives
    Ungroup {
        group_id: EntityId,
        primitive_ids: Vec<EntityId>,
    },
    /// Custom property change
    SetProperty {
        entity_id: EntityId,
        property_name: String,
        old_value: String,
        new_value: String,
    },
}

/// Result of applying a command
#[derive(Debug, Clone)]
pub struct CommandResult {
    /// Whether the command was successful
    pub success: bool,
    /// Events generated by the command
    pub events: Vec<DomainEvent>,
    /// Error message if failed
    pub error: Option<String>,
    /// Time taken to execute
    pub execution_time: Duration,
}

impl CommandResult {
    /// Create a successful result
    pub fn success(events: Vec<DomainEvent>) -> Self {
        Self {
            success: true,
            events,
            error: None,
            execution_time: Duration::ZERO,
        }
    }

    /// Create a failed result
    pub fn failure(error: String) -> Self {
        Self {
            success: false,
            events: Vec::new(),
            error: Some(error),
            execution_time: Duration::ZERO,
        }
    }
}

/// Aggregate root for document state
#[derive(Debug, Clone, Default)]
pub struct DocumentAggregate {
    /// Unique document ID
    pub id: EntityId,
    /// Document name
    pub name: String,
    /// Current version (number of events applied)
    pub version: u64,
    /// Event count for snapshotting
    pub event_count: usize,
    /// Whether the document has unsaved changes
    pub is_dirty: bool,
}

impl DocumentAggregate {
    /// Create a new document aggregate
    pub fn new(id: EntityId, name: String) -> Self {
        Self {
            id,
            name,
            version: 0,
            event_count: 0,
            is_dirty: false,
        }
    }

    /// Apply an event to the aggregate
    pub fn apply(&mut self, event: &DomainEvent) {
        self.version = event.metadata().version;
        self.event_count += 1;
        self.is_dirty = true;
    }

    /// Mark the aggregate as saved
    pub fn mark_saved(&mut self) {
        self.is_dirty = false;
    }

    /// Check if snapshot is needed
    pub fn should_snapshot(&self) -> bool {
        self.event_count >= DEFAULT_SNAPSHOT_THRESHOLD
    }
}
