// ═══════════════════════════════════════════════════════════════════════════════
// ArchFlow Logic - Logic System
//
// This module provides the main LogicSystem that orchestrates:
// 1. Sensor evaluation (detect input events)
// 2. Pulse generation (emit events to PulseBus)
// 3. Actuator execution (respond to pulses)
//
// This is the heart of the Logic Bricks system inspired by Blender's BGE.
//
// Reference: docs/epics/EPIC-001-input-sensors.md - HU-004
// ═══════════════════════════════════════════════════════════════════════════════

#![warn(missing_docs)]

use alloc::vec::Vec;
use archflow_core::EntityId;
use archflow_engine::EntityStore;

use crate::input::{InputEvent, InputSampler};
use crate::mapping::LogicMappingTable;
use crate::pulse::{Pulse, PulseBus, SensorState};
use crate::sensors::{
    DoubleTapSensor, KeyShortcutSensor, LongPressSensor, MouseClickSensor, MouseOverSensor,
    RightClickSensor,
};

/// Main Logic System that evaluates sensors and executes actuators
///
/// This system:
/// 1. Evaluates all sensors with current input
/// 2. Generates pulses for state changes
/// 3. Executes actuators based on wiring table
///
/// # Performance
///
/// - Zero-allocation during hot-path (uses pre-allocated buffers)
/// - Cache-friendly evaluation (sequential access)
/// - Batch processing of all entities in one pass
pub struct LogicSystem {
    /// Input sampler for getting current input state
    input_sampler: InputSampler,

    /// Pulse bus for collecting sensor events
    pulse_bus: PulseBus,

    /// Wiring table connecting sensors to actuators
    wiring: LogicMappingTable,

    /// Mouse sensors for different modes
    mouse_over: MouseOverSensor,
    mouse_click: MouseClickSensor,
    double_tap: DoubleTapSensor,
    long_press: LongPressSensor,
    right_click: RightClickSensor,

    /// Current timestamp in milliseconds
    timestamp: u32,
}

impl LogicSystem {
    /// Create a new LogicSystem
    #[must_use]
    pub fn new() -> Self {
        Self {
            input_sampler: InputSampler::new(),
            pulse_bus: PulseBus::new(),
            wiring: LogicMappingTable::new(),
            mouse_over: MouseOverSensor::new(),
            mouse_click: MouseClickSensor::new(archflow_engine::MAX_ENTITIES),
            double_tap: DoubleTapSensor::new(),
            long_press: LongPressSensor::new(),
            right_click: RightClickSensor::new(),
            timestamp: 0,
        }
    }

    /// Get the input sampler (for JavaScript bridge to set SAB pointer)
    pub fn input_sampler(&mut self) -> &mut InputSampler {
        &mut self.input_sampler
    }

    /// Get the pulse bus (for controller evaluation)
    pub fn pulse_bus(&mut self) -> &mut PulseBus {
        &mut self.pulse_bus
    }

    /// Get the wiring table (for configuring connections)
    pub fn wiring(&mut self) -> &mut LogicMappingTable {
        &mut self.wiring
    }

    /// Update the timestamp for this frame
    pub fn set_timestamp(&mut self, timestamp: u32) {
        self.timestamp = timestamp;
        self.pulse_bus.set_timestamp(timestamp);
    }

    /// Push an input event (for fallback mode when SAB is not available)
    pub fn push_input_event(&mut self, event: InputEvent) {
        self.input_sampler.push_input_event(event);
    }

    /// Evaluate sensors and generate pulses
    ///
    /// This is the main hot-path called every frame:
    /// 1. Sample input from InputSampler
    /// 2. Evaluate all sensors
    /// 3. Generate pulses for state changes
    /// 4. Return pulses for processing
    ///
    /// # Returns
    ///
    /// All pulses generated this frame
    pub fn evaluate_sensors(&mut self, store: &EntityStore) -> Vec<Pulse> {
        let snapshot = self.input_sampler.take_snapshot();
        let mouse_pos = snapshot.mouse_position();
        let buttons = snapshot.buttons;
        let modifiers = snapshot.modifiers;

        // Evaluate mouse sensors
        // Note: In a real implementation, we would iterate over entities
        // and check if the mouse is over each one
        // For now, this is a placeholder for the actual integration

        Vec::new() // Placeholder - pulses will be generated by actual sensors
    }

    /// Execute actuators based on pulses
    ///
    /// This processes all pulses and executes the connected actuators
    pub fn execute_actuators(&mut self, store: &mut EntityStore, pulses: &[Pulse]) {
        for _pulse in pulses {
            // Process each pulse through the wiring table
            // This will be implemented when we have the full wiring table
        }
    }

    /// Main update loop - evaluates sensors and executes actuators
    ///
    /// This is the primary method called each frame
    pub fn update(&mut self, store: &mut EntityStore) {
        // Step 1: Evaluate sensors and generate pulses
        let pulses = self.evaluate_sensors(store);

        // Step 2: Execute actuators based on pulses
        self.execute_actuators(store, &pulses);
    }
}

impl Default for LogicSystem {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use archflow_core::Vec2;

    #[test]
    fn test_logic_system_new() {
        let mut system = LogicSystem::new();
        assert!(!system.input_sampler().is_sab_available());
    }

    #[test]
    fn test_logic_system_set_timestamp() {
        let mut system = LogicSystem::new();
        system.set_timestamp(1000);
        assert_eq!(system.timestamp, 1000);
    }

    #[test]
    fn test_logic_system_push_input_event() {
        let mut system = LogicSystem::new();
        system.push_input_event(InputEvent::MouseMove { x: 100, y: 200 });

        let snapshot = system.input_sampler().take_snapshot();
        assert_eq!(snapshot.mouse_x, 100);
        assert_eq!(snapshot.mouse_y, 200);
    }

    #[test]
    fn test_logic_system_evaluate_sensors() {
        let mut store = EntityStore::new();
        let mut system = LogicSystem::new();
        system.set_timestamp(100);

        // Push some input events
        system.push_input_event(InputEvent::MouseMove { x: 100, y: 100 });
        system.push_input_event(InputEvent::MouseButtonDown { button: 0 });

        // Evaluate sensors
        let pulses = system.evaluate_sensors(&store);
        // Should return pulses (empty for now, will be implemented)
        assert!(pulses.len() >= 0);
    }

    #[test]
    fn test_logic_system_update() {
        let mut store = EntityStore::new();
        let mut system = LogicSystem::new();
        system.set_timestamp(100);

        // Should not panic
        system.update(&mut store);
    }

    #[test]
    fn test_input_sampler_fallback() {
        let mut system = LogicSystem::new();

        // Push events in fallback mode
        system.push_input_event(InputEvent::MouseMove { x: 50, y: 75 });
        system.push_input_event(InputEvent::MouseButtonDown { button: 1 });
        system.push_input_event(InputEvent::KeyDown { keycode: 10 });

        let snapshot = system.input_sampler().take_snapshot();
        assert_eq!(snapshot.mouse_x, 50);
        assert_eq!(snapshot.mouse_y, 75);
        assert!((snapshot.buttons & 0b010) != 0); // Right button
        assert!(snapshot.is_key_pressed(10));
    }

    #[test]
    fn test_pulse_bus_integration() {
        let mut system = LogicSystem::new();
        system.set_timestamp(100);

        // Push some positive pulses
        system.pulse_bus().push_positive(0, 100);
        system.pulse_bus().push_positive(1, 200);

        assert_eq!(system.pulse_bus().len(), 2);

        // Drain pulses
        let pulses = system.pulse_bus().drain();
        assert_eq!(pulses.len(), 2);
        assert_eq!(pulses[0].entity_id, 100);
        assert_eq!(pulses[1].entity_id, 200);

        // Bus should be empty after drain
        assert_eq!(system.pulse_bus().len(), 0);
    }
}
