// ═══════════════════════════════════════════════════════════════════════════════
// ArchFlow Logic - KeyShortcut Sensor Implementation
//
// Epic 2.4: KeyShortcut Sensor
// TDD Cycle: RED → GREEN → REFACTOR
//
// This sensor detects keyboard key presses and combinations with modifiers
// (Ctrl, Shift, Alt, Meta). It uses bitwise operations for efficient modifier tracking.
//
// Performance Characteristics:
// - O(1) key lookup (direct array indexing)
// - Zero-allocation (pre-allocated SignalByte array)
// - Bitwise operations for modifier checking
//
// Memory Impact:
// - 256 bytes (one SignalByte per possible KeyCode)
// - Fixed size regardless of active keys
//
// ═══════════════════════════════════════════════════════════════════════════════

use core::ops::BitOr;

use crate::signals::SignalByte;

/// Keyboard modifier keys
///
/// Uses bitwise operations for efficient checking when multiple
/// modifiers are active simultaneously.
///
/// # Examples
///
/// ```
/// let ctrl_shift = KeyModifiers::CONTROL | KeyModifiers::SHIFT;
/// assert!(ctrl_shift.has_control());
/// assert!(ctrl_shift.has_shift());
/// ```
#[repr(transparent)]
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct KeyModifiers(pub u8);

impl KeyModifiers {
    /// No modifiers active
    pub const EMPTY: Self = Self(0);

    /// Shift key (⇧)
    pub const SHIFT: Self = Self(0b00000001);

    /// Control key (Ctrl)
    pub const CONTROL: Self = Self(0b00000010);

    /// Alt key (Option on Mac, Alt on Windows/Linux)
    pub const ALT: Self = Self(0b00000100);

    /// Meta key (Windows key / Cmd on Mac)
    pub const META: Self = Self(0b00001000);

    /// Returns true if Shift is active
    #[inline(always)]
    #[must_use]
    pub fn has_shift(self) -> bool {
        self.0 & Self::SHIFT.0 != 0
    }

    /// Returns true if Control is active
    #[inline(always)]
    #[must_use]
    pub fn has_control(self) -> bool {
        self.0 & Self::CONTROL.0 != 0
    }

    /// Returns true if Alt is active
    #[inline(always)]
    #[must_use]
    pub fn has_alt(self) -> bool {
        self.0 & Self::ALT.0 != 0
    }

    /// Returns true if Meta is active
    #[inline(always)]
    #[must_use]
    pub fn has_meta(self) -> bool {
        self.0 & Self::META.0 != 0
    }

    /// Returns true if this modifier set contains all flags from `other`
    #[inline(always)]
    #[must_use]
    pub fn contains(self, other: KeyModifiers) -> bool {
        (self.0 & other.0) == other.0
    }

    /// Returns the raw u8 value
    #[inline(always)]
    #[must_use]
    pub const fn bits(self) -> u8 {
        self.0
    }

    /// Returns true if no modifiers are active
    #[inline(always)]
    #[must_use]
    pub fn is_empty(self) -> bool {
        self.0 == 0
    }

    /// Returns true if any modifier is active
    #[inline(always)]
    #[must_use]
    pub fn is_any(self) -> bool {
        self.0 != 0
    }

    /// Returns all modifiers combined (bitwise OR)
    #[inline(always)]
    #[must_use]
    pub const fn all() -> Self {
        Self(Self::SHIFT.0 | Self::CONTROL.0 | Self::ALT.0 | Self::META.0)
    }
}

impl BitOr for KeyModifiers {
    type Output = Self;

    #[inline(always)]
    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

/// Keyboard key codes
///
/// Covers the most commonly used keys for a graphics application.
/// Each key maps to a unique index (0-255) in the KeyShortcutSensor's tracking array.
///
/// # Examples
///
/// ```
/// let key = KeyCode::KeyA;
/// let enter = KeyCode::Enter;
/// let escape = KeyCode::Escape;
/// ```
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum KeyCode {
    // Letters (A-Z)
    KeyA = 0,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,

    // Numbers (0-9)
    Digit0 = 26,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,

    // Special keys
    Enter = 36,
    Escape,
    Space,
    Tab,
    Backspace,
    Delete,

    // Arrow keys
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
}

impl KeyCode {
    /// Returns the index value for this key code
    #[inline(always)]
    #[must_use]
    pub const fn index(self) -> u8 {
        self as u8
    }
}

/// Keyboard event representing a single key state change
///
/// This struct represents the raw input from the keyboard system.
/// It's typically generated by the browser/OS keyboard event handler.
///
/// # Examples
///
/// ```
/// let event = KeyEvent {
///     key: KeyCode::KeyA,
///     modifiers: KeyModifiers::CONTROL,
///     pressed: true,
/// };
/// ```
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct KeyEvent {
    /// The key that changed state
    pub key: KeyCode,

    /// Active modifiers when the key event occurred
    pub modifiers: KeyModifiers,

    /// true if the key was pressed, false if released
    pub pressed: bool,
}

/// Sensor that detects keyboard shortcuts and key combinations
///
/// This sensor tracks the state of all keys and provides methods for:
/// - Detecting individual key presses (rising edge only)
/// - Detecting key combinations with modifiers (Ctrl+S, Shift+A, etc.)
///
/// # Examples
///
/// ```
/// let mut sensor = KeyShortcutSensor::new();
///
/// // Sample Ctrl+S
/// sensor.sample(KeyEvent {
///     key: KeyCode::KeyS,
///     modifiers: KeyModifiers::CONTROL,
///     pressed: true,
/// });
///
/// assert!(sensor.on_key_press(KeyCode::KeyS));
/// assert!(sensor.on_key_combo(&[KeyCode::KeyS], KeyModifiers::CONTROL));
/// ```
///
/// # Performance
///
/// - **Time**: O(1) key lookup via direct array indexing
/// - **Space**: 512 bytes (one SignalByte + one KeyModifiers per KeyCode)
/// - **Allocations**: Zero (pre-allocated on construction)
pub struct KeyShortcutSensor {
    /// Signal history for each possible KeyCode
    ///
    /// Array index corresponds to KeyCode::index()
    /// Each SignalByte stores 6 ticks of key press history
    keys: [SignalByte; 256],

    /// Modifier tracking for each possible KeyCode
    ///
    /// Stores the last modifiers used with each key.
    /// This allows on_key_combo to verify modifier combinations.
    modifiers: [KeyModifiers; 256],
}

impl KeyShortcutSensor {
    /// Creates a new KeyShortcutSensor
    ///
    /// # Examples
    ///
    /// ```
    /// let sensor = KeyShortcutSensor::new();
    /// ```
    #[inline(always)]
    #[must_use]
    pub fn new() -> Self {
        Self {
            keys: [SignalByte::default(); 256],
            modifiers: [KeyModifiers::EMPTY; 256],
        }
    }

    /// Samples a keyboard event and updates internal state
    ///
    /// This should be called for every keyboard event from the system.
    ///
    /// # Arguments
    ///
    /// * `event` - The keyboard event to process
    ///
    /// # Examples
    ///
    /// ```
    /// sensor.sample(KeyEvent {
    ///     key: KeyCode::Enter,
    ///     modifiers: KeyModifiers::EMPTY,
    ///     pressed: true,
    /// });
    /// ```
    #[inline(always)]
    pub fn sample(&mut self, event: KeyEvent) {
        let key_idx = event.key.index();
        self.keys[key_idx as usize].push(event.pressed);
        self.modifiers[key_idx as usize] = event.modifiers;
    }

    /// Detects if a key was just pressed (rising edge)
    ///
    /// Returns true only on the frame when the key transitions from
    /// not pressed to pressed (0 → 1). Holding the key down will not
    /// trigger this repeatedly.
    ///
    /// # Arguments
    ///
    /// * `key` - The key to check
    ///
    /// # Examples
    ///
    /// ```
    /// sensor.sample(KeyEvent { key: KeyCode::Space, pressed: true });
    /// if sensor.on_key_press(KeyCode::Space) {
    ///     // Space bar just pressed
    /// }
    /// ```
    #[inline(always)]
    #[must_use]
    pub fn on_key_press(&self, key: KeyCode) -> bool {
        let key_idx = key.index() as usize;
        self.keys[key_idx].is_rising_edge()
    }

    /// Detects if a key combination is currently active
    ///
    /// This performs an AND check: all specified keys must be pressed,
    /// and the specified modifiers must match exactly.
    ///
    /// # Arguments
    ///
    /// * `keys` - Slice of keys that must all be pressed
    /// * `modifiers` - Required modifiers (bitwise OR of KeyModifiers)
    ///
    /// # Examples
    ///
    /// ```
    /// // Ctrl+S (Save)
    /// assert!(sensor.on_key_combo(
    ///     &[KeyCode::KeyS],
    ///     KeyModifiers::CONTROL
    /// ));
    ///
    /// // Ctrl+Shift+S (Save As)
    /// assert!(sensor.on_key_combo(
    ///     &[KeyCode::KeyS],
    ///     KeyModifiers::CONTROL | KeyModifiers::SHIFT
    /// ));
    ///
    /// // Plain Enter
    /// assert!(sensor.on_key_combo(
    ///     &[KeyCode::Enter],
    ///     KeyModifiers::EMPTY
    /// ));
    /// ```
    #[inline(always)]
    #[must_use]
    pub fn on_key_combo(&self, keys: &[KeyCode], modifiers: KeyModifiers) -> bool {
        // Check that all specified keys are currently pressed
        for &key in keys {
            let key_idx = key.index() as usize;
            if !self.keys[key_idx].get_current() {
                return false;
            }
        }

        // Verify that modifiers match for the first key
        // For multi-key combos, we check that all keys were pressed with the same modifiers
        if !keys.is_empty() {
            let first_key_idx = keys[0].index() as usize;
            let key_modifiers = self.modifiers[first_key_idx];

            // Check that the key's modifiers contain all required modifiers
            // For example: Ctrl+Shift+S pressed when checking Ctrl+S should match
            // (because Ctrl is present), but Shift+S when checking Ctrl+S should not
            if !key_modifiers.contains(modifiers) {
                return false;
            }
        }

        true
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS (inline for verification during development)
// ═════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_key_code_indices() {
        // Verify key indices are correct and don't overlap
        assert_eq!(KeyCode::KeyA.index(), 0);
        assert_eq!(KeyCode::KeyZ.index(), 25);
        assert_eq!(KeyCode::Digit0.index(), 26);
        assert_eq!(KeyCode::Digit9.index(), 35);
        assert_eq!(KeyCode::Enter.index(), 36);
        // F12 is at index 57 (36 + 5 special + 4 arrows + 12 function keys - 1)
        assert_eq!(KeyCode::F12.index(), 57);
    }

    #[test]
    fn test_key_modifiers_bitwise() {
        // Test bitwise operations
        assert_eq!(KeyModifiers::EMPTY.0, 0);

        let shift = KeyModifiers::SHIFT;
        assert_eq!(shift.0, 0b00000001);
        assert!(shift.has_shift());
        assert!(!shift.has_control());

        let ctrl = KeyModifiers::CONTROL;
        assert_eq!(ctrl.0, 0b00000010);
        assert!(ctrl.has_control());
        assert!(!ctrl.has_shift());

        let ctrl_shift = KeyModifiers::CONTROL | KeyModifiers::SHIFT;
        assert!(ctrl_shift.has_control());
        assert!(ctrl_shift.has_shift());
        assert!(!ctrl_shift.has_alt());
        assert!(ctrl_shift.contains(KeyModifiers::CONTROL));
        assert!(ctrl_shift.contains(KeyModifiers::SHIFT));
    }

    #[test]
    fn test_key_modifiers_empty() {
        let empty = KeyModifiers::EMPTY;
        assert!(empty.is_empty());
        assert!(!empty.is_any());
        assert!(!empty.has_shift());
        assert!(!empty.has_control());
        assert!(!empty.has_alt());
        assert!(!empty.has_meta());
    }

    #[test]
    fn test_key_modifiers_all() {
        let all =
            KeyModifiers::SHIFT | KeyModifiers::CONTROL | KeyModifiers::ALT | KeyModifiers::META;
        assert!(all.is_any());
        assert!(all.has_shift());
        assert!(all.has_control());
        assert!(all.has_alt());
        assert!(all.has_meta());
    }

    #[test]
    fn test_sensor_initialization() {
        let sensor = KeyShortcutSensor::new();

        // All keys should start in released state
        assert!(!sensor.on_key_press(KeyCode::KeyA));
        assert!(!sensor.on_key_press(KeyCode::Enter));
        assert!(!sensor.on_key_press(KeyCode::Space));
    }
}
